spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bili?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '123456'
logging:
  level:
    com.example.springboot: info